// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package infrastructure

import (
	"fotongo/infrastructure/services/prisma/db"
)

// Injectors from DepedencyInjection.go:

func NewDatabaseProvider() (*db.PrismaClient, error) {
	prismaClient := db.NewClient()
	return prismaClient, nil
}
