// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"fotongo/api/controllers"
	"fotongo/app/modules/auth"
	"fotongo/infrastructure"
)

import (
	_ "fotongo/docs"
)

// Injectors from DepedencyInjection.go:

func InitializeAuthController() (*controllers.AuthController, error) {
	prismaClient, err := infrastructure.NewDatabaseProvider()
	if err != nil {
		return nil, err
	}
	authInterface := auth.NewAuthService(prismaClient)
	authController := controllers.NewAuthController(authInterface)
	return authController, nil
}
